---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
    annotations:
        github.com/project-slug: $GITHUB_REPO
    description: sail-sharp
    links:
        - icon: github
          title: Repository
          url: https://github.com/$GITHUB_REPO
    name: sail-sharp
spec:
    owner: user:guest
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    annotations:
        github.com/project-slug: $GITHUB_REPO
    description: my-sample-workload
    links:
        - icon: github
          title: Repository
          url: https://github.com/$GITHUB_REPO
        - icon: docs
          title: 'Container image: my-sample-container'
          url: ghcr.io/mathieu-benoit/my-sample-workload:latest
    name: sail-sharp-my-sample-workload
    tags:
        - dotnet
        - http
spec:
    dependsOn:
        - resource:sail-sharp-my-sample-workload-my-dns
        - resource:sail-sharp-my-sample-workload-my-redis
    lifecycle: experimental
    owner: user:guest
    system: sail-sharp
    type: service
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
    description: 'my-dns (type: dns) of my-sample-workload'
    name: sail-sharp-my-sample-workload-my-dns
spec:
    owner: user:guest
    system: sail-sharp
    type: dns
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
    description: 'my-redis (type: redis) of my-sample-workload'
    name: sail-sharp-my-sample-workload-my-redis
spec:
    owner: user:guest
    system: sail-sharp
    type: redis
