---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  annotations:
    github.com/project-slug: mathieu-benoit/sail-sharp
  description: test
  links:
    - icon: github
      title: Repository
      url: https://github.com/mathieu-benoit/sail-sharp
  name: test
spec:
  owner: user:guest
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    github.com/project-slug: mathieu-benoit/sail-sharp
  description: my-sample-workload
  links:
    - icon: github
      title: Repository
      url: https://github.com/mathieu-benoit/sail-sharp
    - icon: docs
      title: 'Container image: my-sample-container'
      url: ghcr.io/mathieu-benoit/my-sample-workload:latest
  name: test-my-sample-workload-2
  tags:
    - dotnet
    - http
spec:
  dependsOn:
  - 'resource:test-my-sample-workload-my-dns'
  lifecycle: experimental
  owner: user:guest
  system: test
  type: service
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  description: test-my-sample-workload-my-dns
  name: test-my-sample-workload-my-dns
spec:
  owner: user:guest
  system: test
  type: dns
