apiVersion: backstage.io/v1alpha1
kind: System
metadata:
    annotations:
        github.com/project-slug: mathieu-benoit/test
    description: test
    links:
        - icon: github
          title: Repository
          url: https://github.com/mathieu-benoit/test
    name: test
spec:
    owner: user:guest
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    annotations:
        github.com/project-slug: mathieu-benoit/test
    description: my-sample-workload
    links:
        - icon: github
          title: Repository
          url: https://github.com/mathieu-benoit/test
        - icon: github
          title: 'Container image: my-sample-container'
          url: ghcr.io/mathieu-benoit/my-sample-workload:latest
    name: test-my-sample-workload
    tags:
        - dotnet
        - http
spec:
    dependsOn:
        - resource:test-my-sample-workload-my-dns
        - resource:test-my-sample-workload-my-redis
    lifecycle: experimental
    owner: user:guest
    system: test
    type: service
