var builder = WebApplication.CreateBuilder(args);
builder.Configuration.AddJsonFile("appsettings.json", true, true);
builder.Configuration.AddEnvironmentVariables();
builder.Services.AddHealthChecks();
var app = builder.Build();
var message = builder.Configuration["MESSAGE"] ?? "Hello, World! (from code)";
var podName = builder.Configuration["POD_NAME"];
var namespaceName = builder.Configuration["NAMESPACE_NAME"];
message = string.IsNullOrEmpty(podName) || string.IsNullOrEmpty(namespaceName) ? message : $"{message} - from {podName} / {namespaceName}";
var platform = System.Runtime.InteropServices.RuntimeInformation.OSArchitecture;
var platformValue = platform == System.Runtime.InteropServices.Architecture.Arm64 ? "arm64" : "amd64" ;
app.MapHealthChecks("/healthz");
app.MapGet("/", () => $"{message} on {platformValue}.");
app.Run();
