apiVersion: score.dev/v1b1
metadata:
  name: my-sample-workload
containers:
  my-sample-container:
    image: .
    resources:
      limits:
        memory: "256Mi"
        cpu: "250m"
      requests:
        memory: "64Mi"
        cpu: "25m"
    variables:
      POD_NAME: "${pod.metadata.name}"
      NAMESPACE_NAME: "${pod.metadata.namespace}"
    files:
      - target: /app/appsettings.json
        mode: "444"
        content: "${resources.env.APP_SETTINGS}"
resources:
  env:
    type: environment
  dns:
    type: dns
  route:
    type: route
    params:
      host: ${resources.dns.host}
      path: /
      port: 8080
service:
  ports:
    tcp:
      port: 8080
      targetPort: 8080
