name: ci-pr
permissions:
  contents: read
on:
  pull_request:
jobs:
  container:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.3.0
      - name: build the application
        run: |
          docker build \
              --tag my-sample-app \
              app/
      - name: run the application
        run: |
          docker run \
              -d \
              -p 8080:8080 \
              --read-only \
              --cap-drop=ALL \
              --user=1000 my-sample-app
      - name: test the application
        run: |
          sleep 10
          curl localhost:8080
