name: ci-pr
permissions:
  contents: read
on:
  pull_request:
env:
  IMAGE_TAG: ${GITHUB_EVENT_NUMBER}
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: build the application
        run: |
          docker build \
              -t ${{ vars.APP_NAME }}:${{ env.IMAGE_TAG }} \
              app/
  test:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: run the container
        run: |
          docker run \
              -d \
              -p 8080:8080 \
              --read-only \
              --cap-drop=ALL \
              --user=1000 \
              ${{ vars.APP_NAME }}:${{ env.IMAGE_TAG }}
      - name: test the container
        run: |
          sleep 10
          curl localhost:8080
  push:
    needs: test
    runs-on: ubuntu-22.04
    steps:
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: '${{ secrets.WI_PROVIDER_ID }}'
          service_account: '${{ secrets.GSA_ID }}'
      - uses: google-github-actions/setup-gcloud@v1
        with:
          version: latest
      - name: prepare environment variables
        run: |
          echo "IMAGE_NAME=${{ secrets.REGISTRY_LOCATION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REGISTRY_NAME }}/${{ vars.APP_NAME }}" >> $GITHUB_ENV
      - name: sign-in to gar
        run: |
          gcloud auth configure-docker ${{ secrets.REGISTRY_LOCATION }}-docker.pkg.dev --quiet
      - name: tag the container
        run: |
         docker tag ${{ vars.APP_NAME }}:${{ env.IMAGE_TAG }} ${IMAGE_NAME}:${{ env.IMAGE_TAG }}
      - name: push the container to gar
        run: |
          docker push \
              ${IMAGE_NAME}:${{ env.IMAGE_TAG }}
