name: deploy-dev
permissions:
  contents: read
on:
  push:
    branches:
      - main
    paths:
      - 'score/**'
      - '.github/workflows/deploy-dev.yml'
env:
  IMAGE_TAG_TO_DEPLOY: v1.3.0
  IMAGE_NAME_TO_DEPLOY: ${{ secrets.REGISTRY_LOCATION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REGISTRY_NAME }}/${{ vars.APP_NAME }}
  ENVIRONMENT_ID: development
jobs:
  job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: create humanitec app
        run: |
          export HUMANITEC_ORG=${{ secrets.HUMANITEC_ORG }}
          export HUMANITEC_TOKEN=${{ secrets.HUMANITEC_TOKEN }}
          
          .github/workflows/bin/humctl create app ${{ vars.APP_NAME }} \
              --context /orgs/${HUMANITEC_ORG} \
              --name ${{ vars.APP_NAME }} \
              || true
      - name: install score-humanitec
        run: |
          SCORE_HUMANITEC_VERSION=$(curl -sL https://api.github.com/repos/score-spec/score-humanitec/releases/latest | jq -r .tag_name)
          wget https://github.com/score-spec/score-humanitec/releases/download/${{ env.SCORE_HUMANITEC_VERSION }}/score-humanitec_${{ env.SCORE_HUMANITEC_VERSION }}_linux_amd64.tar.gz
          tar -xvf score-humanitec_${{ env.SCORE_HUMANITEC_VERSION }}_linux_amd64.tar.gz
          chmod +x score-humanitec
          mv score-humanitec /usr/local/bin
      - name: deploy score-humanitec
        run: |
          sed -i "s,image: ${{ vars.APP_NAME }},image: ${{ env.IMAGE_NAME_TO_DEPLOY }}:${{ env.IMAGE_TAG_TO_DEPLOY }},g" score/score.yaml
          score-humanitec delta \
              --retry \
              --deploy \
              --token ${{ secrets.HUMANITEC_TOKEN }} \
              --org ${{ secrets.HUMANITEC_ORG }} \
              --app ${{ vars.APP_NAME }} \
              --env ${{ env.ENVIRONMENT_ID }} \
              -f score/score.yaml \
              --extensions score/humanitec.score.yaml
