name: open-pr
on:
  pull_request:
permissions:
  contents: read
env:
  SCORE_COMPOSE_VERSION: 'latest'
  SCORE_K8S_VERSION: 'latest'
  WORKLOAD_NAME: my-sample-workload
jobs:
  scan-and-compare:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    steps:
      - name: checkout code in PR branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Docker
        uses: docker/setup-docker-action@1a6edb0ba9ac496f6850236981f15d8f9a82254d # v5.0.0
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
        with:
          version: latest
      - name: docker login docker.io
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: docker login dhi.io
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: dhi.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Build container image on PR branch
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: app/
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: mode=max
          sbom: true
          tags: ${{ env.WORKLOAD_NAME }}:pr-${{ github.event.number }}
      - name: checkout code in main branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: main
      - name: Build container image from main branch
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: app/
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: mode=max
          sbom: true
          tags: ${{ env.WORKLOAD_NAME }}:main
      - name: docker images
        run: |
          docker images
      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@8910519cee8ac046f3ee99686b0dc6654d5ba1a7 # v1.20.3
        with:
          command: compare
          image: local://${{ env.WORKLOAD_NAME }}:pr-${{ github.event.number }}
          to: local://${{ env.WORKLOAD_NAME }}:main
          write-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
  multi-arch-build:
    uses: docker/github-builder/.github/workflows/build.yml@2497a7d1e7d8683af4949c9d6d62012bc16ed59c # v1.5.0
    with:
      output: image
      push: false
      platforms: linux/amd64,linux/arm64
      sbom: true
      cache: true
      context: app/
      set-meta-labels: true
      set-meta-annotations: true
      meta-images: |
        my-sample-workload
      meta-tags: |
        type=ref,event=pr
    secrets:
      registry-auths: |
        - registry: dhi.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
  make-compose-test:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: install score-compose
        uses: score-spec/setup-score@8dce39f07e47ddee44ad7f6699675e12e484ef46 # v3.2.2
        with:
          file: score-compose
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ env.SCORE_COMPOSE_VERSION }}
      - name: docker login dhi.io
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: dhi.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: make compose-up
        run: |
          make compose-up
          sleep 5
      - name: make compose-test
        run: |
          make compose-test
  make-k8s-test:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: docker login dhi.io
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: dhi.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: docker build
        run: |
          docker build -t ${{ env.WORKLOAD_NAME }}:test app/
      - name: make kind-create-cluster
        run: |
          make kind-create-cluster
      - name: make kind-load-image
        run: |
          make kind-load-image
      - name: install score-k8s
        uses: score-spec/setup-score@8dce39f07e47ddee44ad7f6699675e12e484ef46 # v3.2.2
        with:
          file: score-k8s
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ env.SCORE_K8S_VERSION }}
      - name: make k8s-up
        id: k8s-up
        run: |
          make k8s-up
          sleep 5
      - name: make k8s-test
        run: |
          make k8s-test
      - name: catch k8s-up errors
        if: ${{ failure() && steps.k8s-up.outcome == 'failure' }}
        run: |
          kubectl get events
          kubectl logs \
              -l app.kubernetes.io/name=${{ env.WORKLOAD_NAME }}
