name: open-pr
on:
  pull_request:
permissions:
  contents: read
env:
  SCORE_COMPOSE_VERSION: 'latest'
  SCORE_K8S_VERSION: 'latest'
  WORKLOAD_NAME: my-sample-workload
jobs:
  scan-and-compare:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    steps:
      - name: checkout code in PR branch
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up Docker
        uses: docker/setup-docker-action@6d7cfa65f60a9dda7b46e5513fa982536f3c9877 # v5.3.0
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
        with:
          version: latest
      - name: docker login docker.io
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: docker login dhi.io
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: dhi.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Build container image on PR branch
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: app/
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: mode=max
          sbom: true
          tags: ${{ env.WORKLOAD_NAME }}:pr-${{ github.event.number }}
      - name: checkout code in main branch
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: main
      - name: Build container image from main branch
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: app/
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: mode=max
          sbom: true
          tags: ${{ env.WORKLOAD_NAME }}:main
      - name: docker images
        run: |
          docker images
      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@2688993af7bafd6ba8c6a74ec652442be91dd82b # v1.23.1
        with:
          command: compare
          image: local://${{ env.WORKLOAD_NAME }}:pr-${{ github.event.number }}
          to: local://${{ env.WORKLOAD_NAME }}:main
          write-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
  multi-arch-build:
    uses: docker/github-builder/.github/workflows/build.yml@3415a188caae9a0da7fba83bc06985776e0b1790 # v1.14.0
    with:
      output: image
      push: false
      platforms: linux/amd64,linux/arm64
      sbom: true
      cache: true
      context: app/
      set-meta-labels: true
      set-meta-annotations: true
      meta-images: |
        my-sample-workload
      meta-tags: |
        type=ref,event=pr
    secrets:
      registry-auths: |
        - registry: dhi.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
  make-compose-test:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: install score-compose
        uses: score-spec/setup-score@888a7deafd396c3f3f05e00d2d9b0ab225799ac0 # v3.2.4
        with:
          file: score-compose
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ env.SCORE_COMPOSE_VERSION }}
      - name: docker login dhi.io
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: dhi.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: make compose-up
        run: |
          make compose-up
          sleep 5
      - name: make compose-test
        run: |
          make compose-test
  make-k8s-test:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: docker login dhi.io
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: dhi.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: docker build
        run: |
          docker build -t ${{ env.WORKLOAD_NAME }}:test app/
      - name: make kind-create-cluster
        run: |
          make kind-create-cluster
      - name: make kind-load-image
        run: |
          make kind-load-image
      - name: install score-k8s
        uses: score-spec/setup-score@888a7deafd396c3f3f05e00d2d9b0ab225799ac0 # v3.2.4
        with:
          file: score-k8s
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ env.SCORE_K8S_VERSION }}
      - name: make k8s-up
        id: k8s-up
        run: |
          make k8s-up
          sleep 5
      - name: make k8s-test
        run: |
          make k8s-test
      - name: catch k8s-up errors
        if: ${{ failure() && steps.k8s-up.outcome == 'failure' }}
        run: |
          kubectl get events
          kubectl logs \
              -l app.kubernetes.io/name=${{ env.WORKLOAD_NAME }}
