name: Pull Request
on:
  pull_request:
    types:
      - closed
env:
  ENVIRONMENT_ID: pr-${{ github.event.number }}
jobs:
  ob-pr-closed:
    runs-on: ubuntu-latest
    steps:
      - name: checkout humctl bin
        uses: actions/checkout@v3
      - name: delete humanitec env
        run: |
          .github/workflows/bin/humctl delete env ${{ env.ENVIRONMENT_ID }} \
              --token ${{ secrets.HUMANITEC_TOKEN }} \
              --context /orgs/${{ secrets.HUMANITEC_ORG }}/apps/${{ vars.APP_NAME }}
