name: promote-env
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Environment to deploy to
        options: 
        - staging
        - production
env:
  HUMCTL_VERSION: '*'
jobs:
  job:
    runs-on: ubuntu-22.04
    steps:
      - name: install humctl
        uses: humanitec/setup-cli-action@v1
        with:
          version: ${{ env.HUMCTL_VERSION }}
      - name: promote humanitec env
        run: |
          if [ "${{ github.event.inputs.environment }}" == "staging" ]; then
              humctl deploy env development staging \
                  --token ${{ secrets.HUMANITEC_TOKEN }} \
                  --org ${{ secrets.HUMANITEC_ORG }} \
                  --app ${{ vars.APP_NAME }}
          else
              humctl deploy env staging production \
                  --token ${{ secrets.HUMANITEC_TOKEN }} \
                  --org ${{ secrets.HUMANITEC_ORG }} \
                  --app ${{ vars.APP_NAME }}
          fi
      - name: wait for deployment
        run: |
          sleep 1
          IS_DONE=false
          CURRENT_STATUS=""
          while [ "$IS_DONE" = false ]; do
            CURRENT_STATUS=$(humctl get deployment . -o json \
              --token ${{ secrets.HUMANITEC_TOKEN }} \
              --org ${{ secrets.HUMANITEC_ORG }} \
              --app ${{ vars.APP_NAME }} \
              --env ${{ github.event.inputs.environment }} \
              | jq -r .status.status)
            if [ "$CURRENT_STATUS" = "in progress" ]; then
              echo "Deployment still in progress..."
              sleep 1
            elif [ "$CURRENT_STATUS" = "failed" ]; then
              echo "Deployment failed!"
              IS_DONE=true
            else
              echo "Deployment successfully completed!"
              IS_DONE=true
            fi
          done
          echo $CURRENT_STATUS
          if [ "$CURRENT_STATUS" = "failed" ]; then
              exit 1
          fi
