name: test
permissions:
  contents: read
  id-token: write
  packages: write
on:
  workflow_dispatch:
env:
  WORKLOAD_NAME: my-sample-workload
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: login to ghcr
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login \
              ghcr.io \
              -u $ \
              --password-stdin
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: app/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "ghcr.io/${{ github.repository_owner }}/${{ env.WORKLOAD_NAME }}:test"
      - run: |
          docker run -d -p 8080:8080 ghcr.io/${{ github.repository_owner }}/${{ env.WORKLOAD_NAME }}:test
          curl localhost:8080
