name: push-ghcr
permissions:
  contents: read
  packages: write
on:
  push:
    tags:        
      - 'v*'
jobs:
  job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: build the application
        run: |
          docker build \
              --tag ghcr.io/${{ github.repository_owner }}/my-sample-app:latest \
              app/
      - name: login to ghcr
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login \
              ghcr.io \
              -u $ \
              --password-stdin
      - name: push the container in ghcr
        run: |
          docker push \
              ghcr.io/${{ github.repository_owner }}/my-sample-app:latest
