name: push-tag
on:
  push:
    tags:        
      - 'v*'
permissions:
  contents: read # to fetch the repository content
jobs:
  build-push:
    uses: docker/github-builder/.github/workflows/build.yml@abff7868c866c54704b6afa9ad5871948ca97334 # v1.1.0
    permissions:
      id-token: write # to sign attestation(s) with GitHub OIDC Token
      packages: write # to push container image to ghcr
    with:
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      sbom: true
      cache: true
      context: app/
      set-meta-labels: true
      set-meta-annotations: true
      meta-images: |
        ghcr.io/${{ github.repository_owner }}/my-sample-workload
      meta-tags: |
        type=ref,event=tag
        latest
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        - registry: dhi.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
  scan:
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
    needs:
      - build-push
    steps:
      - name: docker login docker.io
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Login to dhi.io
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: dhi.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@f8c776824083494ab0d56b8105ba2ca85c86e4de # v1.18.2
        with:
          command: cves
          sarif-file: sarif.output.json
          summary: true
          image: registry://ghcr.io/${{ github.repository_owner }}/my-sample-workload:${{ github.ref_name }}
      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@c793b717bc78562f491db7b0e93a3a178b099162 # v4.32.5
        with:
          sarif_file: sarif.output.json


